# Backtesting

Imports

In [28]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import statsmodels.api as sm

### Step 1: Load cointegration and price data

In [29]:
data_folder_path = Path("data")
print(data_folder_path.exists())

True

In [30]:
bh_corrected_df = pd.read_parquet(data_folder_path / "bh_corrected_results.parquet")
bh_sig_results_df = bh_corrected_df[bh_corrected_df["bh_reject"]]
sig_results_df = pd.read_parquet(data_folder_path / "sig_results.parquet")

In [31]:
print(sig_results_df.head())

                                 correlation   coint_t   p_value  \
formation_end ticker_0 ticker_1
2016-01-01    STT      GS           0.753596 -3.362022  0.046747
                       MS           0.739525 -4.778833  0.000411
                       LNC          0.776851 -3.481309  0.034089
              COP      EOG          0.781141 -3.454777  0.036620
              KIM      O            0.762781 -4.339056  0.002224

                                 critical_1pct  critical_5pct  critical_10pct  \
formation_end ticker_0 ticker_1
2016-01-01    STT      GS            -3.918346      -3.348304       -3.052893
                       MS            -3.918346      -3.348304       -3.052893
                       LNC           -3.918346      -3.348304       -3.052893
              COP      EOG           -3.918346      -3.348304       -3.052893
              KIM      O             -3.918346      -3.348304       -3.052893

                                 n_observations
formation_end ticker_0 ticker_1
2016-01-01    STT      GS                   504
                       MS                   504
                       LNC                  504
              COP      EOG                  504
              KIM      O                    504

In [32]:
print(bh_corrected_df.head())

                                 correlation   coint_t   p_value  \
formation_end ticker_0 ticker_1
2016-01-01    SWKS     AVGO         0.705393 -0.019827  0.985429
              BAC      STT          0.730833 -2.431513  0.310079
                       HBAN         0.767496 -2.654967  0.216192
                       PFG          0.710855 -2.270825  0.388197
                       TFC          0.756456 -2.563165  0.251944

                                 critical_1pct  critical_5pct  critical_10pct  \
formation_end ticker_0 ticker_1
2016-01-01    SWKS     AVGO          -3.918346      -3.348304       -3.052893
              BAC      STT           -3.918346      -3.348304       -3.052893
                       HBAN          -3.918346      -3.348304       -3.052893
                       PFG           -3.918346      -3.348304       -3.052893
                       TFC           -3.918346      -3.348304       -3.052893

                                 n_observations  bh_reject  bh_p_value
formation_end ticker_0 ticker_1
2016-01-01    SWKS     AVGO                 504      False    0.993327
              BAC      STT                  504      False    0.771795
                       HBAN                 504      False    0.677147
                       PFG                  504      False    0.823731
                       TFC                  504      False    0.711898

In [33]:
historical_ohlcv_df = pd.read_parquet(data_folder_path / "historical_ohlcv_df.parquet")

In [34]:
print(historical_ohlcv_df.head())

Ticker     SOLV                       KVUE                        ...  \
Price      Open High Low Close Volume Open High Low Close Volume  ...
Date                                                              ...
2014-01-02  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...
2014-01-03  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...
2014-01-06  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...
2014-01-07  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...
2014-01-08  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...

Ticker              R                                                 EOG  \
Price            Open       High        Low      Close  Volume       Open
Date
2014-01-02  51.244708  51.384891  50.683965  50.915272  453500  59.113503
2014-01-03  51.055471  51.335842  50.838185  51.020428  303500  58.822462
2014-01-06  51.265752  51.447995  50.186325  50.186325  609800  58.474696
2014-01-07  50.480715  51.244727  50.228386  50.698006  440800  58.581166
2014-01-08  50.683962  50.915269  50.361536  50.873215  468900  58.918288

Ticker
Price            High        Low      Close   Volume
Date
2014-01-02  59.606795  58.222733  58.563427  2943400
2014-01-03  59.141858  58.133981  58.400146  2693800
2014-01-06  58.673431  57.612318  58.208530  3649200
2014-01-07  59.234156  58.098520  59.212864  3286800
2014-01-08  59.560632  58.574047  59.188000  2857800

[5 rows x 3640 columns]

### Step 2: Estimate relationship parameters for all pairs

In [35]:
close_prices = historical_ohlcv_df.xs("Close", level="Price", axis=1)
print(close_prices.head())

Ticker      SOLV  KVUE  SNI  LLL  WBA  EXE       CBRE         MTD  ADT  \
Date
2014-01-02   NaN   NaN  NaN  NaN  NaN  NaN  26.340000  241.529999  NaN
2014-01-03   NaN   NaN  NaN  NaN  NaN  NaN  26.400000  242.710007  NaN
2014-01-06   NaN   NaN  NaN  NaN  NaN  NaN  26.250000  242.419998  NaN
2014-01-07   NaN   NaN  NaN  NaN  NaN  NaN  26.190001  248.360001  NaN
2014-01-08   NaN   NaN  NaN  NaN  NaN  NaN  26.190001  249.669998  NaN

Ticker            IQV  ...        GIS   AMD        CAG       MKTX       SCHW  \
Date                   ...
2014-01-02  45.799999  ...  31.121460  3.95  16.424904  57.739132  22.172007
2014-01-03  46.290001  ...  31.033251  4.00  16.385775  59.292953  22.240696
2014-01-06  46.029999  ...  31.083658  4.13  16.307476  57.483101  22.163406
2014-01-07  46.790001  ...  31.404943  4.18  16.586372  58.030479  21.931561
2014-01-08  47.419998  ...  30.833605  4.18  16.449369  56.794460  22.189175

Ticker            NSC          A         WY          R        EOG
Date
2014-01-02  69.158401  36.233795  19.206179  50.915272  58.563427
2014-01-03  69.203873  36.691479  19.249172  51.020428  58.400146
2014-01-06  68.166222  36.510990  19.052631  50.186325  58.208530
2014-01-07  68.575233  37.033134  19.107903  50.698006  59.212864
2014-01-08  68.098083  37.639080  18.929783  50.873215  59.188000

[5 rows x 705 columns]

Create a function to estimate params for a pair

In [36]:
def estimate_params(ticker_0, ticker_1, formation_start, formation_end):
    pair_prices = close_prices.loc[
        formation_start:(formation_end - pd.DateOffset(days=1)),
        [ticker_0, ticker_1]
    ].dropna()

    y = pair_prices[ticker_0]
    x = pair_prices[ticker_1]

    X = sm.add_constant(x)
    model = sm.OLS(y, X).fit()

    alpha = model.params["const"]
    beta = model.params[ticker_1]

    spread = y - (alpha + beta * x)

    return alpha, beta, spread.mean(), spread.std()

In [37]:
print(estimate_params("AAPL", "MSFT", pd.Timestamp("2020-01-01"), pd.Timestamp("2020-12-31")))

(np.float64(-70.92463045076721), np.float64(0.8908157857894756), np.float64(1.0331065808829393e-13), np.float64(7.600241702353187))

Create a function to estimate params for all pairs in a window and store in a dataframe

In [54]:
def estimate_params_for_window(pairs, formation_start, formation_end):
    results = []

    for ticker_0, ticker_1 in pairs:
        alpha, beta, spread_mean, spread_std = estimate_params(ticker_0, ticker_1, formation_start, formation_end)
        results.append({
            "formation_end": formation_end,
            "ticker_0": ticker_0,
            "ticker_1": ticker_1,
            "alpha": alpha,
            "beta": beta,
            "spread_mean": spread_mean,
            "spread_std": spread_std
        })
    return pd.DataFrame(results).set_index(["formation_end", "ticker_0", "ticker_1"])

Create a function to estimate params for all windows in a dataframe of cointegration data. We will call this function twice: once on the raw p-value threshold data and once on the BH-corrected data.

In [57]:
def estimate_params_for_all_windows(coint_df, window_size=504):
    results = []

    formation_ends = coint_df.index.get_level_values("formation_end").unique()

    for formation_end in formation_ends:
        end_idx = close_prices.index.searchsorted(formation_end, side="left") - 1
        formation_start = close_prices.index[end_idx - (window_size - 1)]

        pairs = coint_df.loc[formation_end].index.tolist()

        window_params_df = estimate_params_for_window(
            pairs,
            formation_start,
            formation_end
        )

        results.append(window_params_df)

    return pd.concat(results, ignore_index=False)

Estimate params for both sig_results_df and bh_corrected_df

In [ ]:
sig_window_params_df = estimate_params_for_all_windows(sig_results_df)
bh_window_params_df = estimate_params_for_all_windows(bh_sig_results_df)

In [59]:
sig_window_params_df.head()

                                     alpha      beta   spread_mean  spread_std
formation_end ticker_0 ticker_1
2016-01-01    STT      GS        15.529639  0.254871  4.398598e-15    1.591031
                       MS        15.050690  1.496055  4.638265e-15    1.330992
                       LNC        9.530159  1.223589  4.391549e-14    1.630143
              COP      EOG       -8.118959  0.813194  1.339317e-13    2.007876
              KIM      O          0.943563  0.495747 -4.854670e-14    0.274850

In [60]:
bh_window_params_df

                                     alpha      beta   spread_mean  spread_std
formation_end ticker_0 ticker_1
2016-01-01    XEL      CMS        3.514142  0.847090  5.465822e-14    0.228813
2016-02-01    XEL      CMS        3.464461  0.849943  4.194881e-14    0.236661
2016-03-01    STT      MS        10.544876  1.664574 -8.238912e-14    1.125561
              XEL      CMS        3.481574  0.849849 -7.390913e-14    0.234388
2016-04-01    STT      MS        11.365390  1.633517 -7.793413e-14    1.122996
...                                    ...       ...           ...         ...
2025-11-01    PPL      NI         8.675948  0.647139  3.207311e-15    0.611207
              CPT      ESS        3.367900  0.392093 -2.774218e-13    2.017918
              RF       KEY       -1.634339  1.484203  2.443196e-14    0.445216
2025-12-01    CPT      ESS        2.656230  0.394576 -7.993606e-14    2.043802
              RF       KEY       -2.206338  1.521070  1.646655e-14    0.419373

[406 rows x 4 columns]

### Simulate trading using formation window data

Calculate z-score from 2 prices

In [43]:
def calculate_z_score(price_0, price_1, alpha, beta, spread_mean, spread_std):
    spread = alpha + beta * price_1 - price_0 # y is ticker_0, x is ticker_1 according to our earlier code
    return (spread - spread_mean) / spread_std

In [ ]:
trade_thresh = 2 # only trade if absolute value of z-score is > 2
sell_thresh = 0.5 # we will sell our current portfolio if absolute value of z score < 0.5

Function to trade within a window for a given df

In [94]:
def simulate_trading_window(params_df, formation_end):
    trading_ohlcv_df = historical_ohlcv_df.loc[
        (historical_ohlcv_df.index >= formation_end) &
        (historical_ohlcv_df.index <= formation_end + pd.DateOffset(months=1))
    ]

    trading_open_df = trading_ohlcv_df.xs('Open', level='Price', axis=1).iloc[:-1] # used for signals
    trading_close_df = trading_ohlcv_df.xs('Close', level='Price', axis=1).iloc[1:] # used for returns

    print(trading_close_df)

In [95]:
simulate_trading_window(sig_window_params_df, pd.Timestamp("2016-01-01"))

Ticker      SOLV  KVUE  SNI  LLL  WBA  EXE       CBRE         MTD  ADT  \
Date
2016-01-05   NaN   NaN  NaN  NaN  NaN  NaN  34.389999  331.380005  NaN
2016-01-06   NaN   NaN  NaN  NaN  NaN  NaN  32.910000  324.739990  NaN
2016-01-07   NaN   NaN  NaN  NaN  NaN  NaN  31.070000  315.730011  NaN
2016-01-08   NaN   NaN  NaN  NaN  NaN  NaN  30.719999  313.929993  NaN
2016-01-11   NaN   NaN  NaN  NaN  NaN  NaN  30.090000  310.859985  NaN
2016-01-12   NaN   NaN  NaN  NaN  NaN  NaN  30.330000  317.019989  NaN
2016-01-13   NaN   NaN  NaN  NaN  NaN  NaN  29.090000  311.579987  NaN
2016-01-14   NaN   NaN  NaN  NaN  NaN  NaN  29.469999  310.660004  NaN
2016-01-15   NaN   NaN  NaN  NaN  NaN  NaN  28.940001  313.619995  NaN
2016-01-19   NaN   NaN  NaN  NaN  NaN  NaN  28.559999  308.429993  NaN
2016-01-20   NaN   NaN  NaN  NaN  NaN  NaN  28.010000  307.450012  NaN
2016-01-21   NaN   NaN  NaN  NaN  NaN  NaN  28.350000  307.079987  NaN
2016-01-22   NaN   NaN  NaN  NaN  NaN  NaN  28.750000  316.250000  NaN
2016-01-25   NaN   NaN  NaN  NaN  NaN  NaN  27.299999  316.019989  NaN
2016-01-26   NaN   NaN  NaN  NaN  NaN  NaN  28.000000  315.230011  NaN
2016-01-27   NaN   NaN  NaN  NaN  NaN  NaN  27.740000  312.850006  NaN
2016-01-28   NaN   NaN  NaN  NaN  NaN  NaN  27.100000  307.399994  NaN
2016-01-29   NaN   NaN  NaN  NaN  NaN  NaN  27.969999  312.850006  NaN
2016-02-01   NaN   NaN  NaN  NaN  NaN  NaN  27.530001  317.320007  NaN

Ticker            IQV  ...        GIS   AMD        CAG        MKTX       SCHW  \
Date                   ...
2016-01-05  67.110001  ...  38.366550  2.75  21.524469   99.136642  27.839991
2016-01-06  66.739998  ...  38.051308  2.51  21.638380   97.938988  26.888117
2016-01-07  65.180000  ...  37.253651  2.28  20.897940   96.408127  25.482151
2016-01-08  65.099998  ...  37.375332  2.14  21.001499   95.210449  25.324963
2016-01-11  64.570000  ...  37.794441  2.34  20.809919   95.921837  25.097908
2016-01-12  65.139999  ...  38.105389  2.39  21.068813   95.705727  25.534546
2016-01-13  63.759998  ...  37.382095  2.25  20.468178   92.662025  24.198429
2016-01-14  63.959999  ...  37.415886  2.21  20.727074   94.048782  24.556479
2016-01-15  63.340000  ...  37.003529  2.03  20.214458   91.644447  23.595875
2016-01-19  63.360001  ...  37.463203  1.95  20.126444   92.193726  23.150503
2016-01-20  63.250000  ...  36.881855  1.80  20.038414   93.031227  22.067648
2016-01-21  62.470001  ...  36.584419  2.09  20.323191   91.770515  21.290424
2016-01-22  63.610001  ...  37.402359  2.02  20.840982   93.022240  22.556679
2016-01-25  63.000000  ...  37.044086  2.12  20.235172   91.824547  21.980316
2016-01-26  63.500000  ...  37.267159  2.07  20.452646   93.994751  22.224840
2016-01-27  61.930000  ...  37.138725  2.13  20.499538   97.506744  22.050179
2016-01-28  60.430000  ...  37.321236  2.08  20.900782  100.829605  21.674673
2016-01-29  60.830002  ...  38.200035  2.20  21.698050  104.665764  22.294701
2016-02-01  60.529999  ...  38.308174  2.14  21.875210  104.242500  22.076384

Ticker            NSC          A         WY          R        EOG
Date
2016-01-05  65.763641  37.283005  19.715807  41.132240  50.436230
2016-01-06  63.533428  37.448498  19.280603  39.293964  48.415325
2016-01-07  62.350399  35.857899  18.568460  37.811733  47.077648
2016-01-08  62.182510  35.480923  18.397020  36.736385  47.120811
2016-01-11  60.727673  34.883289  18.205793  36.663727  45.790325
2016-01-12  60.695694  35.113140  17.816761  37.114201  45.250919
2016-01-13  57.106560  33.890308  17.638718  36.307701  46.273460
2016-01-14  57.674099  34.579884  17.414526  36.598335  47.059467
2016-01-15  57.370350  34.120155  17.025486  35.784538  45.408134
2016-01-19  57.434296  34.202908  16.794703  34.723724  43.973129
2016-01-20  56.898697  34.258083  16.221025  35.108826  43.439507
2016-01-21  56.011436  34.230492  16.484781  35.980732  45.970592
2016-01-22  54.828384  34.920052  16.761726  36.794510  47.607510
2016-01-25  54.140919  34.579884  16.161680  35.544777  44.413010
2016-01-26  55.076160  34.487926  16.319937  38.182289  47.614716
2016-01-27  55.867542  34.064999  16.168272  37.593754  47.643562
2016-01-28  56.043404  33.200718  16.102333  36.983421  49.489590
2016-01-29  56.355133  34.616661  16.887012  38.632782  51.213051
2016-02-01  56.107349  34.653423  17.203522  39.744457  49.821316

[19 rows x 705 columns]